# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'Cocktail' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cocktail

pod 'SnapKit'
pod 'Kingfisher'
pod 'lottie-ios'
pod 'Siren'

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'Firebase/Storage'
pod 'Firebase/Database'

pod 'RxSwift'
pod 'RxCocoa'

end

