# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cocktail' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cocktail

pod 'SnapKit', '~> 5.0.0'
pod 'Kingfisher', '~> 7.0'
pod 'lottie-ios'

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'Firebase/Storage'
pod 'Firebase/Database'

pod 'RxSwift', '6.2.0'
pod 'RxCocoa', '6.2.0'

end

target 'Cocktail WidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cocktail WidgetExtension

end
